### ISSUE TITLE
Rationalize headers from Camel Netty4, Mina2, and HL7 for MLLP.

### ISSUE THREAD

**Issue by jgoodyear** [hqstevenson/camel-mllp#5]
camel-netty4, camel-mina2 and camel-hl7 all set some headers on the messages (in the consumers), We need to decide which headers are appropriate to mimic.

**Comment by hqstevenson** [comment]
Added CamelMllp* headers for values from the message (MllpTcpServerConsumer) - still need to look at Netty Headers

**Comment by hqstevenson** [comment]
Added CamelMllp* exchange properties that allow the TCP connection to be explicitly closed or reset.
