### ISSUE TITLE
Require a Camel Processor that can generate an acknowledgment

### ISSUE THREAD

**Issue by jgoodyear** [hqstevenson/camel-mllp#6]
We do it in my stuff already, but it needs to be exposed. Sometimes we need to tweak the acknowledgment before we send it - the auto stuff won’t always work - it will work 99% of the time, just need to handle the 1%.

**Comment by hqstevenson** [comment]
Added org/apache/camel/processor/mllp/Hl7AcknowledgementGenerator.java
